# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c8db613f6a7b1f1fd167b707bf3b5e0cc0641783539c666f9f6371a627b511c822ca5e3a38d3ec4073cddba1f1c3fc5cb17d6ea6f2eb715207563ae989e513

test:
  secret_key_base: 29791036d40e026ec96053f7ab4ba22e2b84d8cfe0723e47aefad61a7c2b069948866a1706fa7fd9f2292f66da9967254af5691b9c52fcd538056759f7b7c14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
